sudo: required
dist: bionic
language: java

services:
  - docker

jdk:
  - openjdk11

env:
  global:
    - DOCKER_IMAGE=bcesnik/rso-image-uploader:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER

cache:
  directories:
    - "$HOME/.m2"

script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"
