sudo: required
dist: bionic
language: java
services:
- docker
jdk:
- openjdk11
env:
  global:
  - DOCKER_IMAGE=bcesnik/rso_midterm:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: gflT/vWOW51iKR1Lu/0Aubsw3SWuAn9PhO4coIqvMYQDLzUpbDgnzr/pmyEdxbDKguQ61+ijLgOfPIDB8zEul308P+ZxEm6gcYXR6V1tBFfwQWLDE9y+dPXssZSuMUfmJkx4Dt/AeNITfRLyVM+MFsbLV6atn2KSkTtnx+JBTZ6bXd1EDFIB4yxiMeLxaoWFXfJnL+QRDbgmo79+r4a0TrSVRQ58F9KZVjWpjzphhls/kbSSdW/IiUKLu0q1fuwSKlA8jw3XdAGhLovPWxF/lhOXEDLHEVN7XcbGiLkrQJldlz9/yAS7nzmEolSAIODff0bXl1saaJF052rpnTxfwgWqaG7uqw4FsvdnBjDeKi4de5Jr8w/vOp4s9euKfzJJdTYvMqeZlMWkeJfkahLV95d8EI4UeSoVGbqF5ByOJ2btChFroQJLQQKJcG7FzbtEIIbX+MDKzjLNNfm/ywuGWcKwkQQaVKBFwheHs8RcEs13mqCO4fhiB3724V9b1jLX1rslWSwSulWIXL1SWPGZE4T/xr5+9EGyOGgmj4Wl4uuEuxp3hibHCOFdRZVcdz8wH1imAkwttXRIu9SLNbc3Yp6GXvmIs29q55DS/5OZVZ8S0LDoQK0mjTNy1u2/7n5riSZCBWNdhPGUZ8dpXn9Wee1jsgVNWBc2o8ojB8i+MN4=
  - secure: oeUP7bz+vCWC7p644pMw9o64eIzctcBEfMMmFH4abz/568o4JH3DFL64phAvdbI0JyTnbIqzqZaYqAsXyFi2G5aVtTCHE2k2XYqSUy4P/0lCKy2RTt/9vlTo/3E2C0x5Y/e4pdBP97tYU4yUd6HW4ekTLubgExjqpmHG93KMkafSWBvYt9bIrSNtCvL78a7S05lUv+zrsqBtUXxqjkv05V/Gi/bqJikirav1ocoiNqmDmbWtgUdCXorlRB7emKh8vKyCqHwuC7Fsv5Ffj0dGLTnsXjPhzgfIhSy84kJUe6udzWcuvE7/zn0HEYu8hJjg5w4B0myoj3tXV2nNuCxDqNxIuEBsd5/Vyiq84K/hYem+rD2A65+zRfdVzCCjVylYjeRdtWfT/kEPWQXGHyWTnPir1CjO6hrXPCtnfjG3OzGkXzqON/h7Q5CUNMKNDJyHqCTAl53vn/xhCqQxOAwQKu0505ZS/VK881zoQccpgFGSAl2dwO2w9qlTXIjfIgYlDBvYEt+956Em7ECRzeZFHlHfHD+iFc/qt88QOK3RD05q03Pymv96O1VSTn2fWKAH43VOyHcBRDvEJV1MKBC/jIBtyK8iEAwjPQ0ktUG0gxVPfVpPkuCvwGrMWT/uF2nt6zykyNPOvWEEpkcfMxAXRuvj7aflwtzZ8xe4s6nlNdI=
cache:
  directories:
  - "$HOME/.m2"
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"
