apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-midterm-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image-midterm
    spec:
      containers:
      - image: bcesnik/rso_midterm:1.0.0-SNAPSHOT-6.1
        name: image
        ports:
        - containerPort: 8084
          name: server
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: image-midterm
spec:
  type: LoadBalancer
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: images-midterm
