apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
      - image: bcesnik/rso-image-uploader:1.0.0-SNAPSHOT-6.1
        name: image
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: image
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: images
